version: "2"

run:
  # Include test files.
  tests: true

  # List of build tags, all linters use it. Default is empty list.
  build-tags:
    - golangci

  # Allow multiple parallel golangci-lint instances running.
  allow-parallel-runners: true

# Enabled all linters. Conf settings may follow.
linters:
  # Which dirs to skip. Issues from them won't be reported.
  exclusions:
    paths:
      - .github
  default: all

  disable:
  # ---------------------------------------------------------------------------
  # Remove deactivated linters
  # ---------------------------------------------------------------------------
  #
  # ---------------------------------------------------------------------------
  # Disable deprecated/abandoned linters
  # ---------------------------------------------------------------------------
  # deprecated due to new version and replaced by wsl_v5
  - wsl
  # ---------------------------------------------------------------------------
  # Disabled linters with reasons
  # ---------------------------------------------------------------------------
  # Disabled because of testing private functions
  - testpackage
  # Disabled beacuse of external package usage
  - depguard
