run:
  tests: true
  build-tags:
    - golangci
  allow-parallel-runners: true

issues:
  exclude-dirs:
    - .github
    - .vscode

output:
  sort-results: true

linters:
  enable-all: true
  disable:
  # Disable deprecated/abandoned linters
  - golint
  - interfacer
  - ifshort
  - scopelint
  - exhaustivestruct
  - maligned
  - nosnakecase
  - varcheck
  - deadcode
  - structcheck
  # Disable due to mock private functions
  - testpackage
  # Disable due to external dependencies
  - depguard
