run:
  tests: true
  build-tags:
    - golangci
  allow-parallel-runners: true

issues:
  exclude-dirs:
    - .github
    - .vscode

output:
  sort-results: true

linters:
  enable-all: true
  disable:
  # Remobe deprecated and deactivated linters
  #- golint
  #- interfacer
  #- ifshort
  #- scopelint
  #- exhaustivestruct
  #- maligned
  #- nosnakecase
  #- varcheck
  #- deadcode
  #- structcheck
  #- gomnd
  #- execinquery
  #
  # Disable deprecated/abandoned linters
  - exportloopref
  # Disable due to mock private functions
  - testpackage
  # Disable due to external dependencies
  - depguard
