# This workflow runs the unit test (`go test ./...`) on vaious platforms,
# such as: Linux, macOS and Windows.
name: PlatformTests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    name: Unit test

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1'
          check-latest: true

      - name: Create image tag from file hash
        uses: KEINOS/gh-action-hash-for-cache@main
        id: imagetag
        # Udate the hash if Dockerfile/go.mod is changed or the month has changed.
        with:
          path: |
            ./go.mod
            ./.github/Dockerfile
            ./.github/docker-compose.yml
          variant: ${{ runner.os }}$(TZ=UTC-9 date '+%Y%m')

      - name: Use Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ steps.imagetag.outputs.hash }}

      - name: Run unit test
        run: |
          go mod download
          go test -race -v ./...
